Fix Resource Leak When The HTTPResponse Body Is Not Read
http4s/http4s-jdk-http-client pull request #335
Opened 2021-01-16 21:03 UTC by isomarcte

From the JDK docs for HttpResponse#BodyHandlers.ofPublisher,

https://docs.oracle.com/en/java/javase/15/docs/api/java.net.http/java/net/http/HttpResponse.BodyHandlers.html#ofPublisher()

> When the HttpResponse object is returned, the response headers will have been completely read, but the body may not have been fully received yet. The HttpResponse.body() method returns a Publisher<List<ByteBuffer>> from which the body response bytes can be obtained as they are received. The publisher can and must be subscribed to only once.

Of particular note is the final sentence, "The publisher can and must be subscribed to only once.".

There is a much longer discussion on the semantics of this in the comments in the code, but the short version is that we must always ensure that the `Flow.Publisher` returned on the `HttpResponse` when we use `BodyHandlers.ofPublisher` is subscribed to _exactly once_, whether or not anyone reads the body. Once we subscribe, the `Flow.Subscription` must be read or canceled.

Prior to this commit, we weren't doing that in cases where the body was not read, e.g. `Client#status`. For clarification, we _were_ (and still are) interrupting the body stream via a `.interruptWhen` call, but this doesn't subscribe to the `fs2.Stream` if no one has attempted to pull from it yet.

It is _really hard_ to write a unit test to demonstrate this behavior, but thankfully, it is _really easy_ to write some toy code which triggers it. To that end, see https://github.com/isomarcte/http4s-jdk-client-body-resource-leak , which is a repo which has a POC of this error. Running the `Main` method in there should trigger the issue in about 15 seconds. If you locally publish this commit and then re-run that with the this version, it will run forever using constant memory as intended.

For convenience, here are links to the relevant documentation or code,

* https://docs.oracle.com/en/java/javase/15/docs/api/java.net.http/java/net/http/HttpResponse.BodyHandlers.html#ofPublisher()
* https://github.com/typelevel/fs2/blob//reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscriber.scala#L64
    * Note about how fs2 doesn't subscribe until someone starts pulling from the Stream.
* https://github.com/typelevel/fs2/blob//reactive-streams/src/main/scala/fs2/interop/reactivestreams/package.scala#L55
    * Shows how to make a fs2.Stream from a Publisher and attach an effect to the subscription event. This commit uses this to ensure that subscription always happens exactly once.

2021-01-16 21:28 UTC, amesgen commented
Thank you very much! I thought I fixed this in #207, but now I see how that is not the case.

I will review this in detail tomorrow or on monday, to publish a new release ASAP.

2021-01-19 01:12 UTC, amesgen requested changes
Excellent job!

One thing that might be useful is to include an example of how this OOM could be reproduced if we happen to reintroduce it somehow. I agree that writing a unit test is not worth the complexity in this case, so what about adding a suitable main file which can be run manually if desired?

I used [this file](https://gist.github.com/amesgen/760f2d1ca60cf2cb4fde96a14b504ad7) (in `core/src/test/scala/org/http4s/client/jdkhttpclient`) and ran 

```
bloop run core-test --args -J-Xmx200M
```

with and without the changes in `JdkHttpClient`.

2021-01-19 01:12 UTC, amesgen commented on core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala
> +          (Semaphore[F](1L), responseF).tupled
While using a semaphore with 1 permit works perfectly fine, I think it is somewhat nicer to use a `TryableDeferred` here, as this emphasizes that we only have one state transition (from "incomplete" to "complete".

Feel free to use/adapt [this diff](https://gist.github.com/amesgen/4cd0110da0271acdef96685edb1dc97d).

2021-01-19 13:33 UTC, isomarcte commented
Thanks @amesgen for review. I applied your diff (with one minor fix in the comments on a separate commit) and added the Main file. TryableDeferred is a much cleaner solution here.

2021-01-19 13:34 UTC, isomarcte commented
Huh....

This is odd... https://github.com/isomarcte/http4s-jdk-http-client/commits/client-body-resource-leak-fix

Github isn't detecting the new changes on my branch. I've never had that happen before. They are on my fork, but they aren't showing up here.

2021-01-19 14:33 UTC, amesgen approved these changes
Perfect, thanks for fixing the inverted comment!

2021-01-19 14:35 UTC, merged

2021-01-19 14:38 UTC, amesgen commented
Changelog PR open: #338